version: '3.7'

services:

  emsfrontend:
    container_name: emsfrontend
    image: maximilienm/apifrontendlocal
    ports:
      - '1337:80'
    env_file:
      - ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
